hyperskill_project:
  id: 176
  ide_files: https://stepik.org/media/attachments/lesson/518715/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Sun, 13 Jun 2021 14:33:53 UTC
stages:
- id: 905
  step: 12944
  is_completed: false
- id: 906
  step: 12945
  is_completed: false
- id: 907
  step: 12946
  is_completed: false
- id: 908
  step: 12947
  is_completed: false
