hyperskill_project:
  id: 175
  ide_files: https://stepik.org/media/attachments/lesson/517618/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Wed, 19 May 2021 14:20:06 UTC
stages:
- id: 901
  step: 12898
  is_completed: true
- id: 902
  step: 12899
  is_completed: true
- id: 903
  step: 12900
  is_completed: true
- id: 904
  step: 12901
  is_completed: true
topics:
  0:
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: Program execution
    theory_id: 6047
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Introduction to Python shell
    theory_id: 8133
  - title: Naming variables
    theory_id: 5885
  - title: Taking input
    theory_id: 5913
  - title: Program with numbers
    theory_id: 5872
  - title: Invoking a function
    theory_id: 5891
  - title: Declaring a function
    theory_id: 5900
  - title: Arguments
    theory_id: 7248
  - title: If statement
    theory_id: 5953
  - title: For loop
    theory_id: 6065
  - title: Basic data types
    theory_id: 5852
  - title: Integer arithmetic
    theory_id: 5865
  - title: Variables
    theory_id: 5859
  - title: Type casting
    theory_id: 6224
  - title: List
    theory_id: 5979
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Dictionary
    theory_id: 6481
  - title: Dictionary methods
    theory_id: 9008
  1:
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Files
    theory_id: 13025
  - title: Load module
    theory_id: 6019
  - title: Errors
    theory_id: 6052
  - title: Exceptions
    theory_id: 6042
  - title: Math functions
    theory_id: 6256
  - title: Files in Python
    theory_id: 8691
  - title: Built-in exceptions
    theory_id: 11680
  - title: Exception handling
    theory_id: 6270
  2:
  - title: Else statement
    theory_id: 5932
  - title: Elif statement
    theory_id: 5926
  - title: While loop
    theory_id: 5940
  - title: Loop control statements
    theory_id: 6302
  - title: Random module
    theory_id: 6263
  - title: Quotes and multi-line strings
    theory_id: 5814
